author = "Matt Travis"
baseurl = "/"
builddrafts = false
canonifyurls = true
contentdir = "content"
disqusshortname = "cocoaexamplesite"
googleAnalytics = "UA-123-45"
languageCode = "en-US"
layoutdir = "layouts"
pluralizelisttitles = false
publishdir = "public"
pygmentsuseclasses = true
theme = "cocoa"
title = "Matt Travis"
[[menu.main]]
identifier = "code"
name = "Code"
url = "/code/"
weight = -100
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = -110
[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = -120
[params]
author = "Matt Travis"
avatar = "/uploads/2018/02/06/SAM_0047.JPG"
cachebuster = true
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Don't panic"
email = "you@example.space"
extracssfiles = ["/css/override.css"]
faviconfile = "img/leaf.ico"
gatracker = "XYZ"
gitalk = false
gitalk_admin = ["a", "list", "of", "administrator"]
gitalk_clientid = "your client id"
gitalk_clientsecret = "your client secret"
gitalk_owner = "the owner of this repo"
gitalk_repo = "your repo url"
github = "//github.com/you"
highlightjs = true
i18n_flags = false
include_rss = true
initials = "ad"
lang = "en"
latestpostscount = 5
linkedin = "//linkedin.com/in/you"
mastodon = "//example.com/@you"
noshowreadtime = false
piwik = false
px500 = "//500px.com/username"
selfintro = ""
twitter = "//twitter.com/you"
[permalinks]
blog = "blog/:slug/"
